/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DataProvider } from "./DataProvider";
export * as factories from "./factories";
export { DataProvider__factory } from "./factories/DataProvider__factory";
